name: Auto Build
on:
  push:
    branches:
      - release/auto/**
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Build
        uses: actions/setup-node@v1
        with:
          node-version: 16.17.0
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
        working-directory: apps/auto
